version: '3.8'

services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: demodb
      MSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root



#version: '4'
#services:
#  app:
#    container_name: myspring-mysql
#    image: mastilo/anotherimage
#    build: ./
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mysqldb
#  mysqldb:
#    image: mysql
#    ports:
#      - "3307:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=demodb
